# Generated by Django 2.2.5 on 2019-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(default='', max_length=50)),
                ('usuario', models.CharField(max_length=45)),
                ('clave', models.CharField(max_length=50)),
                ('Rol', models.CharField(choices=[('1', 'empleado'), ('2', 'administrador'), ('3', 'usuario')], default='1', max_length=1)),
            ],
        ),
    ]
