# Generated by Django 2.2.5 on 2019-10-11 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(default='', max_length=50)),
                ('usuario', models.CharField(max_length=45, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('Rol', models.CharField(choices=[('1', 'empleado'), ('2', 'administrador'), ('3', 'usuario')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=15, unique=True)),
                ('nombreProducto', models.CharField(max_length=45)),
                ('presentacionProducto', models.CharField(choices=[('1', '330 ml'), ('2', '375ml'), ('3', '750 ml'), ('4', '1000ml'), ('5', '2000')], default='', max_length=1)),
                ('nacionalidad', models.CharField(max_length=45)),
                ('precioVenta', models.FloatField()),
                ('precioCompra', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('habilitado', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorshots.CategoriaProducto')),
            ],
        ),
    ]
