# Generated by Django 2.2.5 on 2019-10-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='presentacionProducto',
            field=models.CharField(choices=[('1', '330 ml'), ('2', '375ml'), ('3', '750 ml'), ('4', '1000ml'), ('5', '2000')], default='', max_length=1),
        ),
    ]
