# Generated by Django 2.2.5 on 2019-09-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoProducto', models.CharField(max_length=15, unique=True)),
                ('nombreProducto', models.CharField(max_length=45)),
                ('precioVenta', models.FloatField()),
                ('precioCompra', models.FloatField()),
                ('habilitado', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
