# Generated by Django 2.2.6 on 2019-11-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='fecha',
            field=models.CharField(default='0000-00-00 00:00:00.000000', max_length=40),
        ),
    ]
