# Generated by Django 2.2.5 on 2019-10-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='presentacionProducto',
            field=models.CharField(choices=[('1', '330 ml'), ('2', '375 ml'), ('3', '750 ml'), ('4', '1000 ml'), ('5', '2000 ml')], default='', max_length=1),
        ),
    ]
