# Generated by Django 2.2.5 on 2019-10-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctorshots', '0002_auto_20191015_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorshots.Mesas')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorshots.Usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorshots.Productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='doctorshots.Ventas')),
            ],
        ),
    ]
